name: rozoom_app
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+8

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter 


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  firebase_core: ^0.4.5
  firebase_auth: ^0.16.1
  firebase_analytics: ^5.0.16
  cloud_firestore: ^0.13.7
  firebase_messaging: ^6.0.16
  shared_preferences:
  http:
  provider: ^4.3.1
  flutter_svg: ^0.17.4
  jitsi_meet: ^0.2.5
  path_provider: ^1.6.11
  flutter_pusher_client: ^0.3.1
  laravel_echo: ^0.2.2
  socket_io_client: ^0.9.1
  image_picker: ^0.6.7+12
  dio: ^3.0.10
  audioplayers: ^0.16.1
  simple_animations: ^2.2.3
  slide_countdown_clock: ^1.0.3
  





dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/auth/blue-circle-hq.png
    - assets/images/auth/boy-hq.png
    - assets/images/logo.png
    - assets/images/index/bg.png
    - assets/images/index/bg2.png
    - assets/images/index/01.png
    - assets/images/index/02.png
    - assets/images/index/03.png
    - assets/images/index/04.png
    - assets/images/index/11.png
    - assets/images/index/12.png
    - assets/images/index/13.png
    - assets/images/index/21.png
    - assets/images/index/22.png
    - assets/images/index/23.png
    - assets/images/index/24.png
    - assets/images/index/25.png
    - assets/images/brand.png
    - assets/images/stats/coin.png
    - assets/images/stats/uah.png
    - assets/images/tasks/right-answer-boy.png
    - assets/images/tasks/wrong-answer-boy.png
    - assets/images/tasks/task-result-points-bg.png
    
    - assets/images/disciplines/1.png
    - assets/images/disciplines/2.png
    - assets/images/disciplines/3.png
    - assets/images/disciplines/4.png
    - assets/images/disciplines/5.png
    - assets/images/disciplines/6.png
    - assets/images/disciplines/7.png
    - assets/images/disciplines/11.png
    - assets/images/disciplines/12.png
    - assets/images/disciplines/13.png
    - assets/images/disciplines/14.png
    - assets/images/disciplines/15.png
    - assets/images/disciplines/16.png
    - assets/images/disciplines/17.png
    - assets/images/disciplines/20.png
    - assets/images/disciplines/21.png
    - assets/images/disciplines/22.png
    - assets/images/disciplines/24.png
    - assets/images/disciplines/26.png
    - assets/images/disciplines/27.png
    - assets/images/disciplines/28.png
    - assets/images/disciplines/30.png
    - assets/images/disciplines/31.png
    - assets/images/disciplines/32.png
    - assets/images/disciplines/33.png
    - assets/images/disciplines/35.png
    - assets/images/disciplines/36.png
    - assets/images/disciplines/37.png
    - assets/images/disciplines/38.png
    - assets/images/disciplines/39.png

    - assets/json/math.json
    - assets/gifs/ripple.gif
    - assets/gifs/spinner.gif
    - assets/gifs/countdown.gif


  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: bip
      fonts:
        - asset: assets/fonts/bip.ttf

    - family: Robot Regular
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf




  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
